services:
  mysql:
    environment:
      MYSQL_DATABASE: app_test
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -proot || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 24

  php:
    environment:
      CI_ENVIRONMENT: testing
    working_dir: /var/www/html
    depends_on:
      mysql:
        condition: service_healthy
